language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kat201/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kat201/react-test npm test

after_success:
  - docker build -t kat201/multi-nginx ./nginx
  - docker build -t kat201/multi-worker ./worker
  - docker build -t kat201/multi-server ./server
  - docker build -t kat201/multi-client ./client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kat201/multi-nginx
  - docker push kat201/multi-worker
  - docker push kat201/multi-server
  - docker push kat201/multi-client

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-030946824495"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
